<div class="mx-auto container p-12 mt-12">
    <div class="bg-white rounded-2xl shadow-lg p-8 md:p-12 max-w-4xl mx-auto my-12 space-y-6">
        <header class="space-y-2 border-b pb-4">
            <h1 class="text-4xl font-extrabold text-gray-800">Privacy Policy</h1>
            <p class="text-sm text-gray-500">Last updated: June 02, 2025</p>
        </header>

        <section class="text-gray-700 space-y-4">
            <p>
                This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
                information when you use our services. It also informs you of your privacy rights and how the law
                protects you.
            </p>
            <p>
                We use your personal data to provide and improve the service. By using the service, you agree to the
                collection and use of information in accordance with this Privacy Policy.
            </p>
        </section>

        <section class="space-y-4">
            <h2 class="text-2xl font-semibold text-gray-800 border-b pb-1">Interpretation and Definitions</h2>

            <div class="space-y-2">
                <h3 class="text-xl font-medium text-gray-800">Interpretation</h3>
                <p class="text-gray-700">
                    Words with the first letter capitalized have meanings defined under the following conditions. These
                    definitions shall apply regardless of whether they appear in singular or plural.
                </p>
            </div>

            <div class="space-y-2">
                <h3 class="text-xl font-medium text-gray-800">Definitions</h3>
                <p class="text-gray-700">
                    For the purposes of this Privacy Policy:
                </p>
            </div>
        </section>
    </div>
    <section class="bg-white rounded-2xl shadow-lg p-8 md:p-12 max-w-4xl mx-auto my-12 space-y-6">
        <h2 class="text-2xl font-semibold text-gray-800 border-b pb-2">Definitions</h2>

        <ul class="space-y-6 list-none text-gray-700">
            <li>
                <p><span class="font-semibold text-gray-900">Account</span> means a unique account created for you to
                    access our Service or parts of our Service.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Affiliate</span> means an entity that controls, is
                    controlled by, or is under common control with a party, where “control” means ownership of 50% or
                    more of the shares, equity interest, or other securities entitled to vote for election of directors
                    or other managing authority.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Company</span> (referred to as either “the Company”, “We”,
                    “Us” or “Our” in this Agreement) refers to Lee Marketing Services, Utalli House, Utalii St, City
                    Centre.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Cookies</span> are small files placed on your computer,
                    mobile device, or any other device by a website, containing details of your browsing history and
                    other uses.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Country</span> refers to: Kenya</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Device</span> means any device that can access the Service
                    such as a computer, cellphone, or digital tablet.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Personal Data</span> is any information that relates to an
                    identified or identifiable individual.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Service</span> refers to the Website.</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Service Provider</span> means any natural or legal person
                    who processes the data on behalf of the Company. This includes third-party companies or individuals
                    employed by the Company to facilitate or analyze the Service, or to perform services related to it.
                </p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Usage Data</span> refers to data collected automatically,
                    either generated by the use of the Service or from the Service infrastructure itself (e.g., duration
                    of a page visit).</p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">Website</span> refers to Lee Marketing Services, accessible
                    at
                    <a href="https://leemarketing.io/" class="text-blue-600 underline hover:text-blue-800"
                        target="_blank" rel="noopener noreferrer">
                        https://leemarketing.io/
                    </a>.
                </p>
            </li>
            <li>
                <p><span class="font-semibold text-gray-900">You</span> means the individual accessing or using the
                    Service, or the company or other legal entity on behalf of which such individual is accessing or
                    using the Service.</p>
            </li>
        </ul>
    </section>

    <section class="bg-white rounded-2xl shadow-lg p-8 md:p-12 max-w-4xl mx-auto my-12 space-y-6 text-gray-700">
        <h2 class="text-2xl font-semibold text-gray-800 border-b pb-2">Usage Data</h2>

        <p>Usage Data is collected automatically when using the Service.</p>

        <p>Usage Data may include information such as your Device’s Internet Protocol (IP) address, browser type and
            version, the pages of our Service that you visit, the time and date of your visit, time spent on those
            pages, unique device identifiers, and other diagnostic data.</p>

        <p>When you access the Service via a mobile device, we may also collect information such as the type of mobile
            device you use, unique mobile ID, mobile IP address, operating system, type of mobile browser, and other
            diagnostic data.</p>

        <p>We may also collect data sent by your browser whenever you visit our Service or access it through a mobile
            device.</p>

        <h2 class="text-2xl font-semibold text-gray-800 border-b pt-8 pb-2">Tracking Technologies and Cookies</h2>

        <p>We use cookies and similar tracking technologies to monitor activity on our Service and store certain
            information. These technologies include beacons, tags, and scripts that help us analyze and improve the
            Service. Technologies we use may include:</p>

        <ul class="list-disc list-inside space-y-4">
            <li>
                <span class="font-semibold text-gray-900">Cookies or Browser Cookies:</span> Small files stored on your
                device. You can set your browser to refuse all cookies or indicate when a cookie is being sent. However,
                if you do not accept cookies, you may not be able to use some parts of our Service. Unless you’ve
                changed your settings to refuse cookies, our Service may use them.
            </li>
            <li>
                <span class="font-semibold text-gray-900">Web Beacons:</span> Certain sections of our Service and emails
                may include small electronic files (e.g., clear gifs, pixel tags, single-pixel gifs) that allow us to
                count users, track email opens, or analyze usage for system integrity.
            </li>
        </ul>

        <p>Cookies can be either <span class="font-medium text-gray-900">Persistent</span> (remain after you go offline)
            or <span class="font-medium text-gray-900">Session</span> (deleted when you close your browser). Learn more
            on
            <a href="" class="text-blue-600 underline hover:text-blue-800" target="_blank"
                rel="noopener noreferrer">
                this article
            </a>.
        </p>

        <p class="font-semibold text-gray-900 pt-4">We use both types of cookies for the following purposes:</p>

        <ul class="space-y-6">
            <li class="bg-gray-50 p-4 rounded-xl shadow-sm">
                <p class="font-semibold text-gray-900">Necessary / Essential Cookies</p>
                <p><span class="text-gray-600">Type:</span> Session Cookies</p>
                <p><span class="text-gray-600">Administered by:</span> Us</p>
                <p>Purpose: To provide essential services, authenticate users, and prevent fraud. Without these cookies,
                    key functionalities cannot be provided.</p>
            </li>

            <li class="bg-gray-50 p-4 rounded-xl shadow-sm">
                <p class="font-semibold text-gray-900">Cookies Policy / Notice Acceptance Cookies</p>
                <p><span class="text-gray-600">Type:</span> Persistent Cookies</p>
                <p><span class="text-gray-600">Administered by:</span> Us</p>
                <p>Purpose: To identify whether users have accepted cookie usage on the Website.</p>
            </li>

            <li class="bg-gray-50 p-4 rounded-xl shadow-sm">
                <p class="font-semibold text-gray-900">Functionality Cookies</p>
                <p><span class="text-gray-600">Type:</span> Persistent Cookies</p>
                <p><span class="text-gray-600">Administered by:</span> Us</p>
                <p>Purpose: To remember your preferences (e.g., login info, language) and provide a more personalized
                    experience on the Website.</p>
            </li>
        </ul>

        <p class="pt-4">For more information about the cookies we use and your choices, please visit our <span
                class="underline text-blue-600 hover:text-blue-800 cursor-pointer">Cookies Policy</span> or the relevant
            section of our Privacy Policy.</p>
    </section>

    <div class="bg-white rounded-2xl shadow-lg p-8 md:p-12 max-w-4xl mx-auto my-12 space-y-6 text-gray-700">
        <!-- Use of Your Personal Data -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Use of Your Personal Data</h3>
            <p class="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul class="list-disc list-inside space-y-2 text-gray-700">
                <li><strong>To provide and maintain our Service</strong>: including to monitor usage.</li>
                <li><strong>To manage Your Account</strong>: enabling access to registered features.</li>
                <li><strong>For performance of a contract</strong>: development, compliance, and execution.</li>
                <li><strong>To contact You</strong>: via email, phone, SMS, or push notifications.</li>
                <li><strong>To provide You</strong> with updates, offers, and relevant information.</li>
                <li><strong>To manage Your requests</strong>: and respond accordingly.</li>
                <li><strong>For business transfers</strong>: in mergers, acquisitions, or restructuring.</li>
                <li><strong>For other purposes</strong>: such as analysis, improvement, and experience enhancement.</li>
            </ul>
        </div>

        <!-- Sharing of Personal Information -->
        <div>
            <p class="mb-4">We may share Your personal information in the following situations:</p>
            <ul class="list-disc list-inside space-y-2 text-gray-700">
                <li><strong>With Service Providers</strong>: for analytics and communications.</li>
                <li><strong>For business transfers</strong>: during corporate restructuring.</li>
                <li><strong>With Affiliates</strong>: who are required to follow this policy.</li>
                <li><strong>With Business Partners</strong>: to provide services or offers.</li>
                <li><strong>With Other Users</strong>: when interacting publicly within the Service.</li>
                <li><strong>With Your Consent</strong>: for other disclosed purposes.</li>
            </ul>
        </div>

        <!-- Retention -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Retention of Your Personal Data</h3>
            <p class="mb-4">We retain Your Personal Data only as long as necessary to fulfill the purposes outlined.
                Certain data may be kept longer for legal obligations, dispute resolution, and policy enforcement.</p>
        </div>

        <!-- Transfers -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Transfer of Your Personal Data</h3>
            <p class="mb-4">Your data may be processed and transferred across regions. We ensure adequate security and
                compliance wherever data is transferred.</p>
        </div>

        <!-- Delete Rights -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Delete Your Personal Data</h3>
            <p class="mb-4">You may delete or request deletion of Your personal data anytime through your account or
                by contacting us. Note: we may retain data when legally required.</p>
        </div>

        <!-- Disclosure -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Disclosure of Your Personal Data</h3>
            <ul class="list-disc list-inside space-y-2 text-gray-700">
                <li><strong>Business Transactions</strong>: data may be transferred with notice.</li>
                <li><strong>Law Enforcement</strong>: when legally required.</li>
                <li><strong>Other Legal Requirements</strong>: to protect rights, investigate wrongdoing, or comply with
                    obligations.</li>
            </ul>
        </div>

        <!-- Security -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Security of Your Personal Data</h3>
            <p class="mb-4">We use commercially acceptable means to secure Your data, but no method is 100% secure.
            </p>
        </div>

        <!-- Children -->
        <div>
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Children's Privacy</h2>
            <p class="mb-4">We do not knowingly collect data from anyone under 13. If discovered, we will delete such
                data promptly.</p>
        </div>

        <!-- External Links -->
        <div>
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Links to Other Websites</h2>
            <p class="mb-4">Our Service may contain links to external sites. We are not responsible for their content
                or privacy policies. Please review their terms separately.</p>
        </div>

        <!-- Changes -->
        <div>
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Changes to This Privacy Policy</h2>
            <p class="mb-4">We may update this Privacy Policy. Updates will be posted here and announced by email or
                within the Service. Review this policy periodically.</p>
        </div>

        <!-- Contact -->
        <div>
            <h2 class="text-2xl font-semibold text-gray-900 mb-4">Contact Us</h2>
            <p class="mb-2">If you have any questions about this Privacy Policy, contact us:</p>
            <ul class="list-disc list-inside text-gray-700">
                <li>By email: <a href="mailto:info@leemarketing.io"
                        class="text-blue-600 hover:underline">info@leemarketing.io</a></li>
            </ul>
        </div>
        <!-- Legal Basis -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Legal Basis for Processing Personal Data</h3>
            <p class="mb-4">We may process your Personal Data under the following legal bases:</p>
            <ul class="list-disc list-inside space-y-2 text-gray-700">
                <li><strong>Consent</strong>: You have given clear permission for processing your personal data for a
                    specific purpose.</li>
                <li><strong>Contract</strong>: Processing is necessary to fulfill a contract we have with you.</li>
                <li><strong>Legal Obligation</strong>: Processing is necessary to comply with the law.</li>
                <li><strong>Legitimate Interests</strong>: Processing is necessary for our legitimate interests unless
                    those interests are overridden by your rights.</li>
            </ul>
        </div>

        <!-- Data Rights -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Your Data Protection Rights</h3>
            <p class="mb-4">Depending on your jurisdiction, you may have the right to:</p>
            <ul class="list-disc list-inside space-y-2 text-gray-700">
                <li>Access and receive a copy of your personal data.</li>
                <li>Request correction of inaccurate or incomplete data.</li>
                <li>Request deletion of your personal data.</li>
                <li>Restrict or object to the processing of your personal data.</li>
                <li>Request transfer of your data to another provider (data portability).</li>
                <li>Withdraw consent at any time where processing is based on your consent.</li>
            </ul>
        </div>

        <!-- Automated Decisions -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Automated Decision-Making and Profiling</h3>
            <p class="mb-4">We do not use your personal data for automated decision-making or profiling that produces
                legal or significant effects.</p>
        </div>

        <!-- Breach Notification -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Data Breach Notification</h3>
            <p class="mb-4">In the event of a data breach, we will notify affected users and regulators as required by
                law. Notifications will include the nature of the breach, potential impacts, and actions taken.</p>
        </div>

        <!-- International Transfers (Expanded) -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">International Transfers of Your Personal Data</h3>
            <p class="mb-4">Your information may be stored and processed in countries outside of your own. We take
                steps to ensure appropriate safeguards are in place when data is transferred internationally, including
                standard contractual clauses or equivalent protection mechanisms.</p>
        </div>

        <!-- Do Not Track -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Do Not Track Signals</h3>
            <p class="mb-4">Our Service does not respond to "Do Not Track" signals. You may manage your privacy
                settings through your browser settings.</p>
        </div>

        <!-- Analytics -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Analytics and Third-Party Tools</h3>
            <p class="mb-4">We may use third-party analytics tools such as Google Analytics or Facebook Pixel to
                understand usage and improve our Service. These tools may collect data such as your IP address, device
                type, and interactions on our site, and are subject to their own privacy policies.</p>
        </div>

        <!-- DPO & Controller -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Data Controller and Contact</h3>
            <p class="mb-2">The Data Controller responsible for your personal data is:</p>
            <ul class="list-disc list-inside text-gray-700">
                <li>Lee Marketing Services, Utalli House, Utalii St, City Centre, Kenya</li>
                <li>Email: <a href="mailto:dpo@leemarketing.io"
                        class="text-blue-600 hover:underline">dpo@leemarketing.io</a></li>
            </ul>
        </div>

        <!-- Consent Withdrawal -->
        <div>
            <h3 class="text-2xl font-semibold text-gray-900 mb-4">Withdrawing Your Consent</h3>
            <p class="mb-4">If we rely on your consent to process your personal data, you may withdraw that consent
                at any time. This does not affect the lawfulness of processing based on consent before its withdrawal.
            </p>
        </div>

    </div>


</div>
